### ISSUE TITLE
Too tall square root when numbers used

### ISSUE THREAD

**Issue by OmarIthawi** [OmarIthawi/arabic-mathjax#10]
The number (8) inside the square root symbol should be lowered down a bit. Script: `\sqrt{8}` . The problem is not there when you have a variable inside the square root. It is only appears when for square roots of simple numeric number.

![image](https://user-images.githubusercontent.com/645156/50539121-71d64580-0b83-11e9-8490-8d7ea25a1e54.png)

Another example with the problem: `\sqrt{456-123}`
But this one is good! : `\sqrt{456-123-x}`

Another example:
![image](https://user-images.githubusercontent.com/645156/50539161-41db7200-0b84-11e9-8b0f-5deda6423faf.png)

**Comment by barillax** [comment]
Hi Omar. Unfortunately, we're seeing a more problematic version of this bug - see screenshot below.

<img width="1120" alt="screen shot 2019-02-12 at 5 54 59 pm" src="https://user-images.githubusercontent.com/29592/52678634-95650d80-2eef-11e9-8e30-611e147fd6d3.png">

We're also seeing it behave properly with variables, but not numbers. However, in tests, the numbers are actually struck through by the top of the square root symbol.

**Comment by OmarIthawi** [comment]
Thanks @barillax for sharing that! The font issues are work in progress now, I'll see if this bug can be solved as well.

**Comment by shadinaif** [comment]
@OmarIthawi ; I believe this PR https://github.com/OmarIthawi/arabic-mathjax/pull/16 is already solving this issue :+1:  (if it is about CommonHTML)

**Comment by OmarIthawi** [comment]
@shadinaif looks like it! Thanks!
