### ISSUE TITLE
\transn breaks vertical spacing inside of a square root

### ISSUE THREAD

**Issue by barillax** [OmarIthawi/arabic-mathjax#19]
As shown below, when you put a decimal number into a square root, wrapped in `\transn`, it displays incorrectly. E.g.: `\sqrt{\transn{0.04}}`

https://codepen.io/barillax/pen/BvVQBX

<img width="1673" alt="Screen Shot 2019-04-01 at 3 22 18 PM" src="https://user-images.githubusercontent.com/29592/55353829-3d2f9e00-5492-11e9-97df-b46297935880.png">

I wonder if the fix for this might be similar to https://github.com/OmarIthawi/arabic-mathjax/pull/16 ?

EDIT: this also happens for `\transt{}{}` inside of a square root, i.e.: `%% \sqrt{{\transt{speed}{السرعة}}} %%`

<img width="1086" alt="Screen Shot 2019-04-01 at 4 02 10 PM" src="https://user-images.githubusercontent.com/29592/55355923-8a623e80-5497-11e9-9d14-494d66f24af2.png">

**Comment by barillax** [comment]
After looking at #16, I inspected the DOM and found that if I added the .mar class to the surrounding element, it fixed the display. See image below illustrating what I mean:

<img width="1672" alt="Screen Shot 2019-04-01 at 3 44 13 PM" src="https://user-images.githubusercontent.com/29592/55355275-d2806180-5495-11e9-85dd-df20a2125f57.png">

The top square root in the above image renders incorrectly, while the bottom one displays properly thanks to the CSS giving the span `border-width: 0.45 em 0;`

I'm not super familiar with the code, but it kind of looks like the issue here is that when you use one of the `\trans*` functions, the resulting token(s) don't have `arabicFontLang` set to `ar`, which leads to the code in https://github.com/OmarIthawi/arabic-mathjax/blob/master/src/html.js#L51 not being run to add the `mar` class?

**Comment by shadinaif** [comment]
@barillax this PR https://github.com/OmarIthawi/arabic-mathjax/pull/20 should solve your issue. Please wait for it to be merged and pushed to npm

CC: @OmarIthawi

**Comment by barillax** [comment]
Thank you @shadinaif !
