### ISSUE TITLE
 how to install this extension on moodle 4.2?

### ISSUE THREAD

**Issue by MELAS007** [OmarIthawi/arabic-mathjax#51]
Dear,

I would like to know if you could help to tell me how to install this extension on moodle 4.2?

I tried by myself but it doesn't work and don't know what I am missing?

Thank in advance

<img width="797" alt="Screen Shot 2024-01-07 at 09 59 11" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/db1b4fb3-4c46-4af1-ae79-63298583a4fd">
<img width="1349" alt="Screen Shot 2024-01-07 at 09 59 34" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/6f49472f-75cd-4cb5-ae4b-3eac89c86da7">
<img width="1076" alt="Screen Shot 2024-01-07 at 10 00 32" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/0539fe5b-6bb5-46ea-b7cc-a1fdd68e6600">

**Comment by MELAS007** [comment]
I think It is solved for arabic language but there is a small issue. Look in below for the sign is not flipping.

any suggestions to make it work.


<img width="915" alt="Screen Shot 2024-01-07 at 11 14 06" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/a740312e-4a25-4b4a-a49c-945a560669c0">
<img width="1036" alt="Screen Shot 2024-01-07 at 11 16 23" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/df8ed8a0-a1a2-4cc3-ad0c-69e50bd8256e">

**Comment by MELAS007** [comment]
Now, it looks fine !  but some issue with arabic letters...

any suggestions for this.

<img width="665" alt="Screen Shot 2024-01-07 at 12 10 39" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/424ffaed-2f63-45a5-9062-08c2e6ca99e2">

**Comment by OmarIthawi** [comment]
@MELAS007 glad to see you've done progress with the plugin.

I only see the output. Would you mind sharing the input so we can check?

**Comment by MELAS007** [comment]
> @MELAS007 glad to see you've done progress with the plugin.
> 
> I only see the output. Would you mind sharing the input so we can check?

When I write the equation in English letter, it get this: 
<img width="1325" alt="Screen Shot 2024-01-07 at 16 06 59" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/5f8fca42-f906-48b9-9362-2713481f9420">
<img width="783" alt="Screen Shot 2024-01-07 at 16 07 30" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/4fe043dd-4155-4f3c-8a7c-269ced6254da">

and when I write with the Arabic letter, it shows like this:
<img width="1352" alt="Screen Shot 2024-01-07 at 16 08 20" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/3476df56-6a10-4657-b131-dbd25df61142">
<img width="792" alt="Screen Shot 2024-01-07 at 16 09 32" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/42799410-3afd-43e5-b44d-c5387cdf63b4">

Reminder : for arabic user will write in arabic and not with english letters. 

I hope to get any suggestions for this.

**Comment by OmarIthawi** [comment]
@MELAS007 What happens if you write `\ar{\sqrt{2}}`?

You're supposed to write in English and then let the plugin converts it to Arabic.

Also, use the Amiri font for better rendering as seen in https://arabicmath.org/testcases/

**Comment by MELAS007** [comment]
> @MELAS007 What happens if you write `\ar{\sqrt{2}}`?
> 
> You're supposed to write in English and then let the plugin converts it to Arabic.
> 
> Also, use the Amiri font for better rendering as seen in https://arabicmath.org/testcases/

It works fine with number. We need with arabic letters. 

<img width="786" alt="Screen Shot 2024-01-07 at 22 46 35" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/0f0ccf0c-96cf-4f3b-b485-6ab417206d85">
<img width="1307" alt="Screen Shot 2024-01-07 at 22 46 54" src="https://github.com/OmarIthawi/arabic-mathjax/assets/16482562/290d5d8d-3b22-494f-abd1-f13701c993af">

**Comment by MELAS007** [comment]
> https://arabicmath.org/testcases/

I tested ( \ar{\tmfrac{x}{y}{z}} ) on the link that you mentioned, You will see it is wrong with letters... it needs to solve because we have many professors will write MATH in arabic letters and not in english letters. I think you know that in arabs countries and in government schools and universities, many professors doesn't know English very well... so they will not understand why they need to write in English in math to appearing in arabic.

**Comment by MELAS007** [comment]
Do you know how to add button with code /alwaysar{f} in mathjax for moodle?

**Comment by OmarIthawi** [comment]
> > https://arabicmath.org/testcases/
> 
> I tested ( \ar{\tmfrac{x}{y}{z}} ) on the link that you mentioned, You will see it is wrong with letters... it needs to solve because we have many professors will write MATH in arabic letters and not in english letters. I think you know that in arabs countries and in government schools and universities, many professors doesn't know English very well... so they will not understand why they need to write in English in math to appearing in arabic.

@MELAS007 this case isn't supported _yet_ in this plugin. I understand what you mean and I think this is something worth supporting in this plugin but it's a big feature that needs to be designed and developed.

Would you mind jumping into a call for discuss the issue? 

Please email me at `omar` at `zeitlabs` dot com.

**Comment by MELAS007** [comment]
> Do you know how to add button with code /alwaysar{f} in mathjax for moodle?

any suggestions about this one?

**Comment by OmarIthawi** [comment]
> > Do you know how to add button with code /alwaysar{f} in mathjax for moodle?
> 
> any suggestions about this one?

I haven't worked with moodle as an engineer, nevertheless I think this is a doable thing to do.

What's the HTML editor in Moodle? Is it TinyMCE?

**Comment by MELAS007** [comment]
> > Do you know how to add button with code /alwaysar{f} in mathjax for moodle?
> 
> any suggestions about this one?

Done!

**Comment by MELAS007** [comment]
> > > Do you know how to add button with code /alwaysar{f} in mathjax for moodle?
> > 
> > 
> > any suggestions about this one?
> 
> I haven't worked with moodle as an engineer, nevertheless I think this is a doable thing to do.
> 
> What's the HTML editor in Moodle? Is it TinyMCE?

I did it! many thanks for your help! but think about the previous subject.... ;)

**Comment by OmarIthawi** [comment]
Great to hear that @MELAS007. 

> but think about the previous subject.... ;)

Supporting Arabic input and Arabic commands is definitely something I'd like to do.

Because this is a non-trivial feature. I propose two options to support this feature:

 - I and my colleagues work with your team to understand the requirements and deliver the feature as a paid project. We've done this multiple times already and the work on this plugin has been almost exclusively funded work via our generous sponsors such as https://www.edraak.org/ , https://salalem.com/ and https://pedago.com/.
 - You and your team develop the feature and we can help in review and guidance. This one can probably be free of charge if the code quality is easy to go with and the work happens smoothly and quickly.

Regardless of the option, the work will be published as opensource so others can benefit from it.

Please note that MathJax v3 has been released years ago and this plugin only supports MathJax v2, because we don't the resource and funding to develop that. It's worth mentioning that because [Moodle might get MathJax v3 support in the future](https://tracker.moodle.org/browse/MDL-66639).

**Comment by MELAS007** [comment]
> Do you know how to add button with code /alwaysar{f} in mathjax for moodle?

done!

**Comment by MELAS007** [comment]
> Great to hear that @MELAS007.
> 
> > but think about the previous subject.... ;)
> 
> Supporting Arabic input and Arabic commands is definitely something I'd like to do.
> 
> Because this is a non-trivial feature. I propose two options to support this feature:
> 
> * I and my colleagues work with your team to understand the requirements and deliver the feature as a paid project. We've done this multiple times already and the work on this plugin has been almost exclusively funded work via our generous sponsors such as https://www.edraak.org/ , https://salalem.com/ and https://pedago.com/.
> * You and your team develop the feature and we can help in review and guidance. This one can probably be free of charge if the code quality is easy to go with and the work happens smoothly and quickly.
> 
> Regardless of the option, the work will be published as opensource so others can benefit from it.
> 
> Please note that MathJax v3 has been released years ago and this plugin only supports MathJax v2, because we don't the resource and funding to develop that. It's worth mentioning that because [Moodle might get MathJax v3 support in the future](https://tracker.moodle.org/browse/MDL-66639).

we do not mind to consider paid project but this would be after we sign a contract with our client. Meanwhile we will do some local trials internally and we hope to reach to a solution.

**Comment by OmarIthawi** [comment]
Great to hear that @MELAS007. You're always welcome to contribute to this repository and I'm happy to review your code.

Are you planning to use MathJax v3? i.e. does Moodle force you to use MathJax v2?

**Comment by MELAS007** [comment]
> Great to hear that @MELAS007. You're always welcome to contribute to this repository and I'm happy to review your code.
> 
> Are you planning to use MathJax v3? i.e. does Moodle force you to use MathJax v2?

I don't know if Moodle can use MathJax V3 but till now I see they use only v2.

**Comment by OmarIthawi** [comment]
> I don't know if Moodle can use MathJax V3 but till now I see they use only v2.

That makes it easier. This plugin only support MathJax v2.

**Comment by minahaleem** [comment]
may i know how you fixed the initial issue with showing the \ar as red text? i stuck on this issue since couple of hours.

**Comment by OmarIthawi** [comment]
@MELAS007 would you mind sharing full instructions on how to add this plugin for Moodle? That'll be a great way to close this issue.

Thanks again.

**Comment by minahaleem** [comment]
Hi,

from my side, i just followed the installation instructions expect the installation of the font

1- Activated the plugin in MathJax - screenshot attached
2- Create a mathematical questions  (both \ar and \alwaysbr) - screenshotattached
3- Expected Results, mathematical equations should be displayed in Arabic, actual results -> ar and alwaysar written in red font 
<img width="426" alt="Bildschirmfoto 2024-02-21 um 16 51 22" src="https://github.com/OmarIthawi/arabic-mathjax/assets/114644666/c59297a1-7858-43fb-adc1-12dcb5079383">
<img width="1161" alt="Bildschirmfoto 2024-02-21 um 16 51 47" src="https://github.com/OmarIthawi/arabic-mathjax/assets/114644666/8984ad94-b0d1-427b-a114-cf46106fb67f">
<img width="1299" alt="Bildschirmfoto 2024-02-21 um 16 52 00" src="https://github.com/OmarIthawi/arabic-mathjax/assets/114644666/4ac2d430-1593-43ec-854b-80baed0c3ebf">

**Comment by MELAS007** [comment]
Here the solution for moodle!

copy this code in below to your Mathjax configuration: 

`MathJax.Ajax.config.path["arabic"] = "https://cdn.rawgit.com/OmarIthawi/arabic-mathjax/v1.2/dist";

MathJax.Hub.Config({
    config: ["Accessible.js", "Safe.js"],
    errorSettings: { message: ["!"] },
    skipStartupTypeset: true,
    messageStyle: "none",
TeX: {
          extensions: ["[arabic]/arabic.js"]
        },
'HTML-CSS': {
        undefinedFamily: 'serif'
    }
});
`
then purge all caches from Development.

I hope that works for you ! 
Regards,

**Comment by minahaleem** [comment]
@MELAS007 thank you very much, it worked just fine. i spent many hours playing with scripts and html scripts without any success, your solution worked as a charm

**Comment by MELAS007** [comment]
> may i know how you fixed the initial issue with showing the \ar as red text? i stuck on this issue since couple of hours.

Did you purge cache from Development ?

**Comment by OmarIthawi** [comment]
Amazing!! This plugin now supports Moodle :)

Thank you both!

I'm happy to see that.
