### ISSUE TITLE
Support for MathJax-node

### ISSUE THREAD

**Issue by SamirElkhatib** [OmarIthawi/arabic-mathjax#6]
Extension does not work with mathjax-node.

Output result gives non-flipped equations. Numerals are replaced and supported, but mflip does not work since it depends on the HTML-CSS processor which is not supported in mathjax-node

**Comment by OmarIthawi** [comment]
Thanks @SamirElkhatib! Could you please provide more context? Screenshots and steps to reproduce are very much appreciated.

Just to let you know, there were no plan to support `mathjax-node`. But this is something that is interesting to add, so probably I'll be able to provide some help, guidance and code review for.

**Comment by barillax** [comment]
For what it's worth, my team is interested in pitching in to help add [CommonHTML](http://docs.mathjax.org/en/latest/options/output-processors/CommonHTML.html) output support to the `arabic-mathjax` project. @OmarIthawi I've sent you an email with some details; we're interested in any guidance you can provide!

**Comment by SamirElkhatib** [comment]
As for using the extension with MathJax node to render HTML-CSS output (server sided), there is a _"hackish"_ workaround:
Node can be used to open up google chrome and inject the Tex input and await MathJax's output...
The approach is a little slow and inefficient, but it might be a good enough solution where a developer only cares about a one time conversion of data.

In my case, I implemented the approach to automatically convert large chunks of Tex data into HTML and store the HTML on the database for direct rendering on my website, where MathJax is no longer needed...

Better implementation could be done using something like JSDOM, however I'm not sure how well it can speak with MathJax, especially when it comes to HTML-CSS output. I'm interested if anyone finds a better solution...

**Comment by SamirElkhatib** [comment]
@OmarIthawi 
Try checking out the [mathjax-node documentation](https://github.com/mathjax/MathJax-node).
You are able to specify the input and the output processors require. For the output, specifying 'html' is translated into CommonHTML, and the project does not include support for HTML-CSS.

The result of this is that whenever Arabic math is used, the characters are translated properly but the flip functionality is not executed. The reason is that the flip depends on the mflip CSS class which is added through the style and called upon when the HTML-CSS Jax signals fire.

Even after switching the signals to use the CommonHTML signals instead, the flipping still does not execute since the styles are not properly added to the CommonHTML output.

I'm not sure if there is something I am missing here, but I think the whole approach will need to change if we were to use CommonHTML

**Comment by OmarIthawi** [comment]
@SamirElkhatib @barillax Thanks for reporting the issue. The Arabic.js Package doesn't support the CommonHTML output yet because it heavily relies on CSS for that matter.

One thing to note, it might make more sense to add such support for the MathJax v3 of the package instead of trying to support the soon-to-be deprecated version of MathJax.

What do you think?

**Comment by OmarIthawi** [comment]
@SamirElkhatib Thank you for reporting the issue.

I wanted to let you know that #7 has been merged. PR #7 adds support for the CommonHTML output, which I believe solves the issues with MathJax-node integration.

Please feel free to re-open the issue (or create a new one).
